services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/beerscanner
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - JWT_SECRET=${JWT_SECRET:-defaultSecretKey}
#      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
#      - MAIL_USERNAME=${MAIL_USERNAME}
#      - MAIL_PASSWORD=${MAIL_PASSWORD}
#    restart: unless-stopped
#    volumes:
#      - app-data:/tmp

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=beerscanner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  selenium-hub:
    image: selenium/hub:4.33.0 # Match Selenium version with your client
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
#    networks:
#      - selenium-net

  chrome-node:
    image: selenium/node-chrome:4.21.0 # Match Selenium version
    container_name: chrome-node
    shm_size: '2g' # Recommended for Chrome
#    depends_on:
#      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1 # Optional: if you want to VNC into the browser node for debugging
      # - SCREEN_WIDTH=1920 # Optional
      # - SCREEN_HEIGHT=1080 # Optional
#    networks:
#      - selenium-net

volumes:
  postgres-data:
  app-data: